import type { Metadata, Viewport } from 'next'

export const viewport: Viewport = {
	colorScheme: 'light dark',
}

export const metadata: Metadata = {
	metadataBase: new URL('http://localhost:3000'),
	title: {
		default: 'Create Next App',
		template: '%s | CNA',
	},
	description: 'Generated by create next app',
	alternates: {
		canonical: '/',
	},
}
